// <auto-generated />
using System;
using CS4760GrantApplication.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CS4760GrantApplication.Migrations
{
    [DbContext(typeof(CS4760GrantApplicationContext))]
    [Migration("20260615153014_GrantAcknowledgements")]
    partial class GrantAcknowledgements
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CS4760GrantApplication.Models.BudgetItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FundingSource")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GrantId")
                        .HasColumnType("int");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GrantId");

                    b.ToTable("BudgetItems");
                });

            modelBuilder.Entity("CS4760GrantApplication.Models.College", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DeanId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DeanId");

                    b.ToTable("Colleges");
                });

            modelBuilder.Entity("CS4760GrantApplication.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChairId")
                        .HasColumnType("int");

                    b.Property<int?>("CollegeId")
                        .HasColumnType("int");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ChairId");

                    b.HasIndex("CollegeId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("CS4760GrantApplication.Models.Grant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Acknowledgement1")
                        .HasColumnType("bit");

                    b.Property<bool>("Acknowledgement2")
                        .HasColumnType("bit");

                    b.Property<bool>("Acknowledgement3")
                        .HasColumnType("bit");

                    b.Property<bool>("Acknowledgement4")
                        .HasColumnType("bit");

                    b.Property<int?>("CollegeId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("InvolvesHumanOrAnimalSubjects")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSaved")
                        .HasColumnType("bit");

                    b.Property<string>("Justification")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OpenedTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProjectImpact")
                        .HasColumnType("int");

                    b.Property<string>("ProjectSummary")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectTimeline")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Signature")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SignatureDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SuccessEvaluation")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<bool>("isMultipleDepartments")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CollegeId");

                    b.HasIndex("UserId");

                    b.ToTable("Grants");
                });

            modelBuilder.Entity("CS4760GrantApplication.Models.GrantAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GrantId")
                        .HasColumnType("int");

                    b.Property<bool>("IsApprovalFile")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("GrantId");

                    b.ToTable("GrantAttachments");
                });

            modelBuilder.Entity("CS4760GrantApplication.Models.RatingSuggestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("RubricCriterionId")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RubricCriterionId");

                    b.ToTable("RatingSuggestions");
                });

            modelBuilder.Entity("CS4760GrantApplication.Models.RubricCriterion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("MaxScore")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("RubricCriteria");
                });

            modelBuilder.Entity("CS4760GrantApplication.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CollegeId")
                        .HasColumnType("int");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCommitteeChair")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCommitteeMember")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("CollegeId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DepartmentGrant", b =>
                {
                    b.Property<int>("DepartmentsId")
                        .HasColumnType("int");

                    b.Property<int>("GrantsId")
                        .HasColumnType("int");

                    b.HasKey("DepartmentsId", "GrantsId");

                    b.HasIndex("GrantsId");

                    b.ToTable("DepartmentGrant");
                });

            modelBuilder.Entity("CS4760GrantApplication.Models.BudgetItem", b =>
                {
                    b.HasOne("CS4760GrantApplication.Models.Grant", "Grant")
                        .WithMany("BudgetItems")
                        .HasForeignKey("GrantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grant");
                });

            modelBuilder.Entity("CS4760GrantApplication.Models.College", b =>
                {
                    b.HasOne("CS4760GrantApplication.Models.User", "Dean")
                        .WithMany()
                        .HasForeignKey("DeanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Dean");
                });

            modelBuilder.Entity("CS4760GrantApplication.Models.Department", b =>
                {
                    b.HasOne("CS4760GrantApplication.Models.User", "Chair")
                        .WithMany()
                        .HasForeignKey("ChairId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CS4760GrantApplication.Models.College", "College")
                        .WithMany()
                        .HasForeignKey("CollegeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Chair");

                    b.Navigation("College");
                });

            modelBuilder.Entity("CS4760GrantApplication.Models.Grant", b =>
                {
                    b.HasOne("CS4760GrantApplication.Models.College", "College")
                        .WithMany("Grants")
                        .HasForeignKey("CollegeId");

                    b.HasOne("CS4760GrantApplication.Models.User", "User")
                        .WithMany("Grants")
                        .HasForeignKey("UserId");

                    b.Navigation("College");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CS4760GrantApplication.Models.GrantAttachment", b =>
                {
                    b.HasOne("CS4760GrantApplication.Models.Grant", "Grant")
                        .WithMany("Attachments")
                        .HasForeignKey("GrantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grant");
                });

            modelBuilder.Entity("CS4760GrantApplication.Models.RatingSuggestion", b =>
                {
                    b.HasOne("CS4760GrantApplication.Models.RubricCriterion", null)
                        .WithMany("RatingSuggestions")
                        .HasForeignKey("RubricCriterionId");
                });

            modelBuilder.Entity("CS4760GrantApplication.Models.User", b =>
                {
                    b.HasOne("CS4760GrantApplication.Models.College", "College")
                        .WithMany()
                        .HasForeignKey("CollegeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CS4760GrantApplication.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("College");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("DepartmentGrant", b =>
                {
                    b.HasOne("CS4760GrantApplication.Models.Department", null)
                        .WithMany()
                        .HasForeignKey("DepartmentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CS4760GrantApplication.Models.Grant", null)
                        .WithMany()
                        .HasForeignKey("GrantsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CS4760GrantApplication.Models.College", b =>
                {
                    b.Navigation("Grants");
                });

            modelBuilder.Entity("CS4760GrantApplication.Models.Grant", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("BudgetItems");
                });

            modelBuilder.Entity("CS4760GrantApplication.Models.RubricCriterion", b =>
                {
                    b.Navigation("RatingSuggestions");
                });

            modelBuilder.Entity("CS4760GrantApplication.Models.User", b =>
                {
                    b.Navigation("Grants");
                });
#pragma warning restore 612, 618
        }
    }
}
